
//Common(通用行为，可能被多个组建所响应)
const ACTION_COMMON_CHANGE_LOGIN_STATE = 'ACTION_COMMON_CHANGE_LOGIN_STATE';


//Header
const ACTION_HEADER_CHANGE_SELECTED_KEY = 'ACTION_HEADER_CHANGE_SELECTED_KEY';


export {
    ACTION_HEADER_CHANGE_SELECTED_KEY,
    ACTION_COMMON_CHANGE_LOGIN_STATE,
}