
//Common(通用行为，可能被多个组建所响应)
const ACTION_COMMON_CHANGE_LOGIN_STATE = 'ACTION_COMMON_CHANGE_LOGIN_STATE';


//Header
const ACTION_HEADER_BEGIN_LOGIN = 'ACTION_HEADER_BEGIN_LOGIN';
const ACTION_HEADER_LOGIN_FINISHED = 'ACTION_HEADER_LOGIN_FINISH';
const ACTION_HEADER_BEGIN_REGISTER = 'ACTION_HEADER_BEGIN_REGISTER';
const ACTION_HEADER_REGISTER_FINISHED = 'ACTION_HEADER_REGISTER_FINISHED';


//Home
const ACTION_HOME_BEGIN_GET_TASK_LIST = 'ACTION_HOME_BEGIN_GET_TASK_LIST';
const ACTION_HOME_GET_TASK_LIST_FINISH = 'ACTION_HOME_GET_TASK_LIST_FINISH';
const ACTION_HOME_CHANGE_ORDER_BY = 'ACTION_HOME_CHANGE_ORDER_BY';
const ACTION_HOME_CHANGE_UP_OR_DOWN = 'ACTION_HOME_CHANGE_UP_OR_DOWN';

export {
    ACTION_COMMON_CHANGE_LOGIN_STATE,
    ACTION_HEADER_BEGIN_LOGIN,
    ACTION_HEADER_BEGIN_REGISTER,
    ACTION_HEADER_LOGIN_FINISHED,
    ACTION_HEADER_REGISTER_FINISHED,
    ACTION_HOME_BEGIN_GET_TASK_LIST,
    ACTION_HOME_GET_TASK_LIST_FINISH,
    ACTION_HOME_CHANGE_ORDER_BY,
    ACTION_HOME_CHANGE_UP_OR_DOWN,
}